name: pet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: 7.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  auto_route_generator: 7.3.2
  build_runner: 2.4.8

flutter:
  uses-material-design: true
